/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 03/08/2024 17:47:11          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'fbclient.dll';

CREATE DATABASE 'LOCACAO'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR CLIENTES;
CREATE GENERATOR LOCACAO;
CREATE GENERATOR LOCACAO_VEICULOS;
CREATE GENERATOR VEICULOS;


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CLIENTES (
    ID           INTEGER NOT NULL,
    NOME         VARCHAR(100) NOT NULL,
    DOCUMENTO    VARCHAR(15) NOT NULL,
    CEP          VARCHAR(8),
    LOGRADOURO   VARCHAR(20),
    COMPLEMENTO  VARCHAR(20),
    NUMERO       VARCHAR(10),
    BAIRRO       VARCHAR(20),
    CIDADE       VARCHAR(20),
    UF           VARCHAR(2),
    TELEFONE     VARCHAR(11) NOT NULL
);

CREATE TABLE LOCACAO (
    ID              INTEGER NOT NULL,
    ID_CLIENTE      INTEGER NOT NULL,
    DATA_LOCACAO    TIMESTAMP,
    DATA_DEVOLUCAO  TIMESTAMP,
    TOTAL           NUMERIC(11,2),
    "HASH"          VARCHAR(300)
);

CREATE TABLE LOCACAO_VEICULOS (
    ID          INTEGER NOT NULL,
    ID_LOCACAO  INTEGER NOT NULL,
    ID_VEICULO  INTEGER NOT NULL,
    VALOR       NUMERIC(11,2)
);

CREATE TABLE VEICULOS (
    ID      INTEGER NOT NULL,
    NOME    VARCHAR(100),
    VALOR   NUMERIC(11,2),
    PLACA   VARCHAR(10),
    STATUS  VARCHAR(20)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID);
ALTER TABLE LOCACAO ADD CONSTRAINT PK_LOCACAO PRIMARY KEY (ID);
ALTER TABLE LOCACAO_VEICULOS ADD CONSTRAINT PK_LOCACAO_VEICULOS PRIMARY KEY (ID);
ALTER TABLE VEICULOS ADD CONSTRAINT PK_VEICULOS PRIMARY KEY (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CLIENTES_BI0 */
CREATE OR ALTER TRIGGER CLIENTES_BI0 FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
   NEW.ID = NEXT VALUE FOR CLIENTES;
END
^

/* Trigger: LOCACAO_BI */
CREATE OR ALTER TRIGGER LOCACAO_BI FOR LOCACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(LOCACAO,1);
END
^

/* Trigger: LOCACAO_VEICULOS_BI */
CREATE OR ALTER TRIGGER LOCACAO_VEICULOS_BI FOR LOCACAO_VEICULOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(LOCACAO_VEICULOS,1);
END
^

/* Trigger: VEICULOS_BI */
CREATE OR ALTER TRIGGER VEICULOS_BI FOR VEICULOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(VEICULOS,1);
END
^

SET TERM ; ^

